In [1]:
import Pkg
Pkg.activate(@__DIR__)
Pkg.instantiate()

include("../test/integrals.jl")

  Activating project at `~/repos/WaveGreen2D/notebooks`
  Activating project at `~/repos/WaveGreen2D/test`


HL₂ (generic function with 1 method)

In [2]:
L₁([0.0, 0.0, 1.0])

-0.8359079217559051

In [3]:
L₂([0.0, 0.0, 1.0])

-0.1880896827357042

In [4]:
HL₁([0.0, 0.0, 1.0])

(-0.8359079217559051, [0.0, 0.0, 0.36755451564226865], [0.22910621828028072 0.0 0.0; 0.0 -0.22910621828028072 0.0; 0.0 0.0 0.08432644541653952])

In [5]:
HL₂([0.0, 0.0, 1.0])

(-0.18808968273570414, [0.0, 0.8409654195801465, -0.31437632351802436], [0.13814079870013432 0.0 0.0; 0.0 -0.13814079870013435 0.6590345804198534; 0.0 0.6590345804198534 -0.5518118762628742])

In [6]:
for (i, v) in enumerate([1, 2, 3])
    println(i, v)
end

11
22
33


In [8]:
a = zeros(3, 3)

3×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [9]:
a[1:2, 1:2]

2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0

In [11]:
using StaticArrays

In [14]:
a = SVector{3, Float64}(1, 2, 3)

3-element SVector{3, Float64} with indices SOneTo(3):
 1.0
 2.0
 3.0

In [15]:
a[1:2]

2-element Vector{Float64}:
 1.0
 2.0

In [18]:
1.0 + eps() == 1.0

false

In [22]:
x = [1, 2, 3]
i = 1

H = i == 1 ? x[3] : exp(x[3])


3

In [23]:

using Random

In [24]:
lb = SVector{3, Float64}(0.0, 0.0, 1e-2)
ub = SVector{3, Float64}(0.5, 1.0, 7.0)
npts = 2
points = [lb .+ rand(SVector{3,Float64}) .* (ub .- lb) for _ in 1:npts]

2-element Vector{SVector{3, Float64}}:
 [0.02914678275575605, 0.6720681886415844, 1.5068337294387006]
 [0.49331398566426526, 0.2081702554516417, 4.968529221373219]